export {default as Hero} from './Hero'
export {default as Philosophy} from './Philosophy'
export {default as Categories} from './Categories'
export {default as HookProject} from './HookProject'
export {default as FinalCTA} from './FinalCTA'
export {default as  SettingsBar} from '../SettingsBar'